### ISSUE TITLE
Add Website link in the About section

### ISSUE THREAD

**Issue by sri-nivas1227** [Sushants-Git/Quizzical#2]
You can add a link to the hosted app in the about section like this👇🏻 
![image](https://github.com/Sushants-Git/Quizzical/assets/83027963/90cf61f7-ba56-49eb-98f6-e5ff9c61e943)

It is better than adding it in the README file.

**Comment by sri-nivas1227** [comment]
And also, can you provide good documentation about the project. Like, goals of the project, how you can contribute to the project, Expecting features and currently facing bugs. So we can have an idea about how we can contribute to the project.

**Comment by Sushants-Git** [comment]
Hey @sri-nivas1227, thanks a lot for looking into the website. Added the website link into the About section. I will update the documentation by tomorrow. Thanks for letting me know about these issues !!!

**Comment by sri-nivas1227** [comment]
Yeah great. Would love to contribute if you can provide documentation.

**Comment by Sushants-Git** [comment]
> Yeah great. Would love to contribute if you can provide documentation.

Hey @sri-nivas1227, sorry for the delay i finally wrote the documentation for the app. Would be really happy if you could contribute to it !!

I am closing this Issue since both the tasks ( i.e. adding a website link and the documentation have been completed. )
